// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: api/proto/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_CreateRun_FullMethodName       = "/oblivious.agent.v1.AgentService/CreateRun"
	AgentService_ExecuteReAct_FullMethodName    = "/oblivious.agent.v1.AgentService/ExecuteReAct"
	AgentService_ContinueBudget_FullMethodName  = "/oblivious.agent.v1.AgentService/ContinueBudget"
	AgentService_ApproveToolCall_FullMethodName = "/oblivious.agent.v1.AgentService/ApproveToolCall"
	AgentService_ContinuePlan_FullMethodName    = "/oblivious.agent.v1.AgentService/ContinuePlan"
	AgentService_AdjustPlan_FullMethodName      = "/oblivious.agent.v1.AgentService/AdjustPlan"
	AgentService_ApprovePlanStep_FullMethodName = "/oblivious.agent.v1.AgentService/ApprovePlanStep"
	AgentService_ExecutePlanStep_FullMethodName = "/oblivious.agent.v1.AgentService/ExecutePlanStep"
	AgentService_SkipPlanStep_FullMethodName    = "/oblivious.agent.v1.AgentService/SkipPlanStep"
	AgentService_RetryPlanStep_FullMethodName   = "/oblivious.agent.v1.AgentService/RetryPlanStep"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService 处理 Agent 执行
type AgentServiceClient interface {
	// CreateRun 创建 Agent 运行
	CreateRun(ctx context.Context, in *CreateRunRequest, opts ...grpc.CallOption) (*CreateRunResponse, error)
	// ExecuteReAct 执行 ReAct 循环
	ExecuteReAct(ctx context.Context, in *ExecuteReActRequest, opts ...grpc.CallOption) (*ExecuteReActResponse, error)
	// ContinueBudget 使用新的 token budget 恢复运行
	ContinueBudget(ctx context.Context, in *ContinueBudgetRequest, opts ...grpc.CallOption) (*ContinueBudgetResponse, error)
	// ApproveToolCall 批准工具调用
	ApproveToolCall(ctx context.Context, in *ApproveToolCallRequest, opts ...grpc.CallOption) (*ApproveToolCallResponse, error)
	// ContinuePlan 继续执行已批准的规划步骤
	ContinuePlan(ctx context.Context, in *PlanRunRequest, opts ...grpc.CallOption) (*PlanRunResponse, error)
	// AdjustPlan 调整剩余规划步骤
	AdjustPlan(ctx context.Context, in *AdjustPlanRequest, opts ...grpc.CallOption) (*PlanRunResponse, error)
	// ApprovePlanStep 批准规划步骤
	ApprovePlanStep(ctx context.Context, in *PlanStepActionRequest, opts ...grpc.CallOption) (*PlanStepActionResponse, error)
	// ExecutePlanStep 执行规划步骤
	ExecutePlanStep(ctx context.Context, in *PlanStepActionRequest, opts ...grpc.CallOption) (*PlanStepActionResponse, error)
	// SkipPlanStep 跳过规划步骤
	SkipPlanStep(ctx context.Context, in *PlanStepActionRequest, opts ...grpc.CallOption) (*PlanStepActionResponse, error)
	// RetryPlanStep 重试失败的规划步骤
	RetryPlanStep(ctx context.Context, in *PlanStepActionRequest, opts ...grpc.CallOption) (*PlanStepActionResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateRun(ctx context.Context, in *CreateRunRequest, opts ...grpc.CallOption) (*CreateRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRunResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecuteReAct(ctx context.Context, in *ExecuteReActRequest, opts ...grpc.CallOption) (*ExecuteReActResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteReActResponse)
	err := c.cc.Invoke(ctx, AgentService_ExecuteReAct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ContinueBudget(ctx context.Context, in *ContinueBudgetRequest, opts ...grpc.CallOption) (*ContinueBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContinueBudgetResponse)
	err := c.cc.Invoke(ctx, AgentService_ContinueBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ApproveToolCall(ctx context.Context, in *ApproveToolCallRequest, opts ...grpc.CallOption) (*ApproveToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveToolCallResponse)
	err := c.cc.Invoke(ctx, AgentService_ApproveToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ContinuePlan(ctx context.Context, in *PlanRunRequest, opts ...grpc.CallOption) (*PlanRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanRunResponse)
	err := c.cc.Invoke(ctx, AgentService_ContinuePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AdjustPlan(ctx context.Context, in *AdjustPlanRequest, opts ...grpc.CallOption) (*PlanRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanRunResponse)
	err := c.cc.Invoke(ctx, AgentService_AdjustPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ApprovePlanStep(ctx context.Context, in *PlanStepActionRequest, opts ...grpc.CallOption) (*PlanStepActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanStepActionResponse)
	err := c.cc.Invoke(ctx, AgentService_ApprovePlanStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecutePlanStep(ctx context.Context, in *PlanStepActionRequest, opts ...grpc.CallOption) (*PlanStepActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanStepActionResponse)
	err := c.cc.Invoke(ctx, AgentService_ExecutePlanStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SkipPlanStep(ctx context.Context, in *PlanStepActionRequest, opts ...grpc.CallOption) (*PlanStepActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanStepActionResponse)
	err := c.cc.Invoke(ctx, AgentService_SkipPlanStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RetryPlanStep(ctx context.Context, in *PlanStepActionRequest, opts ...grpc.CallOption) (*PlanStepActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanStepActionResponse)
	err := c.cc.Invoke(ctx, AgentService_RetryPlanStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService 处理 Agent 执行
type AgentServiceServer interface {
	// CreateRun 创建 Agent 运行
	CreateRun(context.Context, *CreateRunRequest) (*CreateRunResponse, error)
	// ExecuteReAct 执行 ReAct 循环
	ExecuteReAct(context.Context, *ExecuteReActRequest) (*ExecuteReActResponse, error)
	// ContinueBudget 使用新的 token budget 恢复运行
	ContinueBudget(context.Context, *ContinueBudgetRequest) (*ContinueBudgetResponse, error)
	// ApproveToolCall 批准工具调用
	ApproveToolCall(context.Context, *ApproveToolCallRequest) (*ApproveToolCallResponse, error)
	// ContinuePlan 继续执行已批准的规划步骤
	ContinuePlan(context.Context, *PlanRunRequest) (*PlanRunResponse, error)
	// AdjustPlan 调整剩余规划步骤
	AdjustPlan(context.Context, *AdjustPlanRequest) (*PlanRunResponse, error)
	// ApprovePlanStep 批准规划步骤
	ApprovePlanStep(context.Context, *PlanStepActionRequest) (*PlanStepActionResponse, error)
	// ExecutePlanStep 执行规划步骤
	ExecutePlanStep(context.Context, *PlanStepActionRequest) (*PlanStepActionResponse, error)
	// SkipPlanStep 跳过规划步骤
	SkipPlanStep(context.Context, *PlanStepActionRequest) (*PlanStepActionResponse, error)
	// RetryPlanStep 重试失败的规划步骤
	RetryPlanStep(context.Context, *PlanStepActionRequest) (*PlanStepActionResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) CreateRun(context.Context, *CreateRunRequest) (*CreateRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRun not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteReAct(context.Context, *ExecuteReActRequest) (*ExecuteReActResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteReAct not implemented")
}
func (UnimplementedAgentServiceServer) ContinueBudget(context.Context, *ContinueBudgetRequest) (*ContinueBudgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContinueBudget not implemented")
}
func (UnimplementedAgentServiceServer) ApproveToolCall(context.Context, *ApproveToolCallRequest) (*ApproveToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveToolCall not implemented")
}
func (UnimplementedAgentServiceServer) ContinuePlan(context.Context, *PlanRunRequest) (*PlanRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContinuePlan not implemented")
}
func (UnimplementedAgentServiceServer) AdjustPlan(context.Context, *AdjustPlanRequest) (*PlanRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustPlan not implemented")
}
func (UnimplementedAgentServiceServer) ApprovePlanStep(context.Context, *PlanStepActionRequest) (*PlanStepActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApprovePlanStep not implemented")
}
func (UnimplementedAgentServiceServer) ExecutePlanStep(context.Context, *PlanStepActionRequest) (*PlanStepActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePlanStep not implemented")
}
func (UnimplementedAgentServiceServer) SkipPlanStep(context.Context, *PlanStepActionRequest) (*PlanStepActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SkipPlanStep not implemented")
}
func (UnimplementedAgentServiceServer) RetryPlanStep(context.Context, *PlanStepActionRequest) (*PlanStepActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryPlanStep not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_CreateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateRun(ctx, req.(*CreateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecuteReAct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteReActRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecuteReAct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExecuteReAct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecuteReAct(ctx, req.(*ExecuteReActRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ContinueBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ContinueBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ContinueBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ContinueBudget(ctx, req.(*ContinueBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ApproveToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ApproveToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ApproveToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ApproveToolCall(ctx, req.(*ApproveToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ContinuePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ContinuePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ContinuePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ContinuePlan(ctx, req.(*PlanRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AdjustPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AdjustPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AdjustPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AdjustPlan(ctx, req.(*AdjustPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ApprovePlanStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanStepActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ApprovePlanStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ApprovePlanStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ApprovePlanStep(ctx, req.(*PlanStepActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecutePlanStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanStepActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecutePlanStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExecutePlanStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecutePlanStep(ctx, req.(*PlanStepActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SkipPlanStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanStepActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SkipPlanStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SkipPlanStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SkipPlanStep(ctx, req.(*PlanStepActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RetryPlanStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanStepActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RetryPlanStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RetryPlanStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RetryPlanStep(ctx, req.(*PlanStepActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oblivious.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRun",
			Handler:    _AgentService_CreateRun_Handler,
		},
		{
			MethodName: "ExecuteReAct",
			Handler:    _AgentService_ExecuteReAct_Handler,
		},
		{
			MethodName: "ContinueBudget",
			Handler:    _AgentService_ContinueBudget_Handler,
		},
		{
			MethodName: "ApproveToolCall",
			Handler:    _AgentService_ApproveToolCall_Handler,
		},
		{
			MethodName: "ContinuePlan",
			Handler:    _AgentService_ContinuePlan_Handler,
		},
		{
			MethodName: "AdjustPlan",
			Handler:    _AgentService_AdjustPlan_Handler,
		},
		{
			MethodName: "ApprovePlanStep",
			Handler:    _AgentService_ApprovePlanStep_Handler,
		},
		{
			MethodName: "ExecutePlanStep",
			Handler:    _AgentService_ExecutePlanStep_Handler,
		},
		{
			MethodName: "SkipPlanStep",
			Handler:    _AgentService_SkipPlanStep_Handler,
		},
		{
			MethodName: "RetryPlanStep",
			Handler:    _AgentService_RetryPlanStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/agent.proto",
}
