// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateKnowledgeBaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseRequest) Reset() {
	*x = CreateKnowledgeBaseRequest{}
	mi := &file_api_proto_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseRequest) ProtoMessage() {}

func (x *CreateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_proto_rawDescGZIP(), []int{0}
}

func (x *CreateKnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type CreateKnowledgeBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KbId          string                 `protobuf:"bytes,1,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseResponse) Reset() {
	*x = CreateKnowledgeBaseResponse{}
	mi := &file_api_proto_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseResponse) ProtoMessage() {}

func (x *CreateKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKnowledgeBaseResponse) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *CreateKnowledgeBaseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UploadDocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KbId           string                 `protobuf:"bytes,1,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	DocumentName   string                 `protobuf:"bytes,2,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	Content        []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	OrganizationId string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_api_proto_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_proto_rawDescGZIP(), []int{2}
}

func (x *UploadDocumentRequest) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *UploadDocumentRequest) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *UploadDocumentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadDocumentRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type UploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	mi := &file_api_proto_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_proto_rawDescGZIP(), []int{3}
}

func (x *UploadDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UploadDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RetrieveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KbId           string                 `protobuf:"bytes,1,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	TopK           int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	OrganizationId string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_api_proto_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_proto_rawDescGZIP(), []int{4}
}

func (x *RetrieveRequest) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*RetrievedChunk      `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_api_proto_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_proto_rawDescGZIP(), []int{5}
}

func (x *RetrieveResponse) GetChunks() []*RetrievedChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type RetrievedChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedChunk) Reset() {
	*x = RetrievedChunk{}
	mi := &file_api_proto_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedChunk) ProtoMessage() {}

func (x *RetrievedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedChunk.ProtoReflect.Descriptor instead.
func (*RetrievedChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_proto_rawDescGZIP(), []int{6}
}

func (x *RetrievedChunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RetrievedChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrievedChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_proto_rag_proto protoreflect.FileDescriptor

const file_api_proto_rag_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/rag.proto\x12\x10oblivious.rag.v1\"{\n" +
	"\x1aCreateKnowledgeBaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\"J\n" +
	"\x1bCreateKnowledgeBaseResponse\x12\x13\n" +
	"\x05kb_id\x18\x01 \x01(\tR\x04kbId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x94\x01\n" +
	"\x15UploadDocumentRequest\x12\x13\n" +
	"\x05kb_id\x18\x01 \x01(\tR\x04kbId\x12#\n" +
	"\rdocument_name\x18\x02 \x01(\tR\fdocumentName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\"Q\n" +
	"\x16UploadDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"z\n" +
	"\x0fRetrieveRequest\x12\x13\n" +
	"\x05kb_id\x18\x01 \x01(\tR\x04kbId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\"L\n" +
	"\x10RetrieveResponse\x128\n" +
	"\x06chunks\x18\x01 \x03(\v2 .oblivious.rag.v1.RetrievedChunkR\x06chunks\"a\n" +
	"\x0eRetrievedChunk\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score2\xb8\x02\n" +
	"\n" +
	"RAGService\x12r\n" +
	"\x13CreateKnowledgeBase\x12,.oblivious.rag.v1.CreateKnowledgeBaseRequest\x1a-.oblivious.rag.v1.CreateKnowledgeBaseResponse\x12c\n" +
	"\x0eUploadDocument\x12'.oblivious.rag.v1.UploadDocumentRequest\x1a(.oblivious.rag.v1.UploadDocumentResponse\x12Q\n" +
	"\bRetrieve\x12!.oblivious.rag.v1.RetrieveRequest\x1a\".oblivious.rag.v1.RetrieveResponseB\"Z oblivious/api/proto/rag/v1;ragv1b\x06proto3"

var (
	file_api_proto_rag_proto_rawDescOnce sync.Once
	file_api_proto_rag_proto_rawDescData []byte
)

func file_api_proto_rag_proto_rawDescGZIP() []byte {
	file_api_proto_rag_proto_rawDescOnce.Do(func() {
		file_api_proto_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rag_proto_rawDesc), len(file_api_proto_rag_proto_rawDesc)))
	})
	return file_api_proto_rag_proto_rawDescData
}

var file_api_proto_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_rag_proto_goTypes = []any{
	(*CreateKnowledgeBaseRequest)(nil),  // 0: oblivious.rag.v1.CreateKnowledgeBaseRequest
	(*CreateKnowledgeBaseResponse)(nil), // 1: oblivious.rag.v1.CreateKnowledgeBaseResponse
	(*UploadDocumentRequest)(nil),       // 2: oblivious.rag.v1.UploadDocumentRequest
	(*UploadDocumentResponse)(nil),      // 3: oblivious.rag.v1.UploadDocumentResponse
	(*RetrieveRequest)(nil),             // 4: oblivious.rag.v1.RetrieveRequest
	(*RetrieveResponse)(nil),            // 5: oblivious.rag.v1.RetrieveResponse
	(*RetrievedChunk)(nil),              // 6: oblivious.rag.v1.RetrievedChunk
}
var file_api_proto_rag_proto_depIdxs = []int32{
	6, // 0: oblivious.rag.v1.RetrieveResponse.chunks:type_name -> oblivious.rag.v1.RetrievedChunk
	0, // 1: oblivious.rag.v1.RAGService.CreateKnowledgeBase:input_type -> oblivious.rag.v1.CreateKnowledgeBaseRequest
	2, // 2: oblivious.rag.v1.RAGService.UploadDocument:input_type -> oblivious.rag.v1.UploadDocumentRequest
	4, // 3: oblivious.rag.v1.RAGService.Retrieve:input_type -> oblivious.rag.v1.RetrieveRequest
	1, // 4: oblivious.rag.v1.RAGService.CreateKnowledgeBase:output_type -> oblivious.rag.v1.CreateKnowledgeBaseResponse
	3, // 5: oblivious.rag.v1.RAGService.UploadDocument:output_type -> oblivious.rag.v1.UploadDocumentResponse
	5, // 6: oblivious.rag.v1.RAGService.Retrieve:output_type -> oblivious.rag.v1.RetrieveResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_rag_proto_init() }
func file_api_proto_rag_proto_init() {
	if File_api_proto_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rag_proto_rawDesc), len(file_api_proto_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rag_proto_goTypes,
		DependencyIndexes: file_api_proto_rag_proto_depIdxs,
		MessageInfos:      file_api_proto_rag_proto_msgTypes,
	}.Build()
	File_api_proto_rag_proto = out.File
	file_api_proto_rag_proto_goTypes = nil
	file_api_proto_rag_proto_depIdxs = nil
}
