#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

assert_file_exists() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "[quality-gates] missing file: $path" >&2
    exit 1
  fi
}

assert_file_contains() {
  local path="$1"
  local pattern="$2"
  if ! rg -q --fixed-strings -- "$pattern" "$path"; then
    echo "[quality-gates] expected pattern '$pattern' in $path" >&2
    exit 1
  fi
}

assert_file_not_contains() {
  local path="$1"
  local pattern="$2"
  if rg -q --fixed-strings -- "$pattern" "$path"; then
    echo "[quality-gates] unexpected pattern '$pattern' in $path" >&2
    exit 1
  fi
}

assert_file_not_matches() {
  local path="$1"
  local pattern="$2"
  if rg -q -- "$pattern" "$path"; then
    echo "[quality-gates] unexpected regex '$pattern' in $path" >&2
    exit 1
  fi
}

assert_file_count_at_least() {
  local path="$1"
  local pattern="$2"
  local minimum="$3"
  local count

  count=$(rg --fixed-strings --count -- "$pattern" "$path" || true)
  if [[ -z "$count" ]]; then
    count=0
  fi

  if (( count < minimum )); then
    echo "[quality-gates] expected at least $minimum occurrences of '$pattern' in $path; found $count" >&2
    exit 1
  fi
}

workflow_file="$repo_root/.github/workflows/ci.yml"
workspace_file="$repo_root/pnpm-workspace.yaml"
gitignore_file="$repo_root/.gitignore"
package_file="$repo_root/package.json"
readme_file="$repo_root/README.md"
api_file="$repo_root/docs/API.md"
contracts_file="$repo_root/docs/architecture/current-system-contracts.md"
release_checklist_file="$repo_root/docs/release/rc-checklist.md"
commercial_gates_file="$repo_root/docs/release/commercial-gates.md"
relay_route_table_file="$repo_root/docs/release/relay-route-table.md"
phase16_verification_file="$repo_root/.planning/phases/16-relay-authority-evidence-and-v05-closeout/16-VERIFICATION.md"
deployment_remediation_file="$repo_root/docs/release/deployment-runtime-remediation.md"
backup_restore_runbook_file="$repo_root/docs/release/backup-restore-runbook.md"
observability_slos_file="$repo_root/docs/release/observability-slos.md"
release_rollback_runbook_file="$repo_root/docs/release/release-rollback-runbook.md"
incident_response_runbook_file="$repo_root/docs/release/incident-response-runbook.md"
disaster_recovery_runbook_file="$repo_root/docs/release/disaster-recovery-runbook.md"
v07_operations_evidence_file="$repo_root/docs/release/v07-operations-evidence.md"
product_overview_file="$repo_root/docs/product/public-overview.md"
product_onboarding_file="$repo_root/docs/product/onboarding.md"
product_pricing_file="$repo_root/docs/product/pricing.md"
product_operator_guide_file="$repo_root/docs/product/operator-guide.md"
dockerfile_server_file="$repo_root/Dockerfile.server"
dockerfile_web_file="$repo_root/Dockerfile.web"
dockerfile_postgres_pgvector_file="$repo_root/Dockerfile.postgres-pgvector"
dockerignore_file="$repo_root/.dockerignore"
compose_file="$repo_root/docker-compose.yml"
deploy_smoke_file="$repo_root/scripts/deploy-smoke.sh"
deploy_validate_file="$repo_root/scripts/deploy-validate.sh"
backup_postgres_file="$repo_root/scripts/backup-postgres.sh"
restore_postgres_file="$repo_root/scripts/restore-postgres.sh"
backup_restore_smoke_file="$repo_root/scripts/backup-restore-smoke.sh"
relay_security_file="$repo_root/scripts/verify-relay-security.sh"
k8s_namespace_file="$repo_root/deploy/kubernetes/namespace.yaml"
k8s_configmap_file="$repo_root/deploy/kubernetes/configmap.yaml"
k8s_secret_example_file="$repo_root/deploy/kubernetes/secret.example.yaml"
k8s_postgres_file="$repo_root/deploy/kubernetes/postgres.yaml"
k8s_redis_file="$repo_root/deploy/kubernetes/redis.yaml"
k8s_server_file="$repo_root/deploy/kubernetes/server.yaml"
k8s_web_file="$repo_root/deploy/kubernetes/web.yaml"
observability_alerts_file="$repo_root/deploy/observability/prometheus-alerts.yaml"
observability_dashboard_file="$repo_root/deploy/observability/grafana-dashboard.json"
owner_matrix_file="$repo_root/docs/governance/owner-matrix.md"
weekly_status_file="$repo_root/docs/governance/weekly-status-template.md"
blocker_escalation_file="$repo_root/docs/governance/blocker-escalation.md"
check_script="$repo_root/scripts/check.sh"
test_script="$repo_root/scripts/test.sh"
builtin_mcp_file="$repo_root/src/server/internal/mcp/builtin.go"
agent_workflow_migration_file="$repo_root/src/server/migrations/0031_agent_workflow_runs.sql"
agent_store_file="$repo_root/src/server/internal/agent/store.go"
agent_store_test_file="$repo_root/src/server/internal/agent/store_test.go"
agent_service_test_file="$repo_root/src/server/internal/agent/service_test.go"
agent_http_handler_test_file="$repo_root/src/server/internal/http/agent_handler_test.go"
phase25_context_file="$repo_root/.planning/phases/25-mcp-tool-commercial-behavior/25-CONTEXT.md"
phase25_plan_file="$repo_root/.planning/phases/25-mcp-tool-commercial-behavior/25-01-PLAN.md"
phase26_context_file="$repo_root/.planning/phases/26-durable-agent-workflows/26-CONTEXT.md"
phase26_plan_file="$repo_root/.planning/phases/26-durable-agent-workflows/26-01-PLAN.md"
phase26_verification_file="$repo_root/.planning/phases/26-durable-agent-workflows/26-VERIFICATION.md"
phase26_summary_file="$repo_root/.planning/phases/26-durable-agent-workflows/26-01-SUMMARY.md"
knowledge_rag_migration_file="$repo_root/src/server/migrations/0032_knowledge_rag_index.sql"
knowledge_service_file="$repo_root/src/server/internal/knowledge/service.go"
knowledge_store_file="$repo_root/src/server/internal/knowledge/store.go"
knowledge_service_test_file="$repo_root/src/server/internal/knowledge/service_test.go"
knowledge_store_test_file="$repo_root/src/server/internal/knowledge/store_test.go"
knowledge_http_handler_test_file="$repo_root/src/server/internal/http/knowledge_handler_test.go"
knowledge_router_file="$repo_root/src/server/internal/http/router.go"
knowledge_web_page_file="$repo_root/src/web/src/routes/workspace/KnowledgePage.tsx"
knowledge_web_test_file="$repo_root/src/web/src/routes/workspace/KnowledgePage.test.tsx"
web_api_types_file="$repo_root/src/web/src/types/api.ts"
phase27_context_file="$repo_root/.planning/phases/27-knowledge-product-promise-alignment/27-CONTEXT.md"
phase27_plan_file="$repo_root/.planning/phases/27-knowledge-product-promise-alignment/27-01-PLAN.md"
phase27_verification_file="$repo_root/.planning/phases/27-knowledge-product-promise-alignment/27-VERIFICATION.md"
phase27_summary_file="$repo_root/.planning/phases/27-knowledge-product-promise-alignment/27-01-SUMMARY.md"
phase28_context_file="$repo_root/.planning/phases/28-commercial-ux-and-journey-hardening/28-CONTEXT.md"
phase28_plan_file="$repo_root/.planning/phases/28-commercial-ux-and-journey-hardening/28-01-PLAN.md"
phase28_verification_file="$repo_root/.planning/phases/28-commercial-ux-and-journey-hardening/28-VERIFICATION.md"
phase28_summary_file="$repo_root/.planning/phases/28-commercial-ux-and-journey-hardening/28-01-SUMMARY.md"
phase29_context_file="$repo_root/.planning/phases/29-public-docs-onboarding-pricing-and-operator-guides/29-CONTEXT.md"
phase29_plan_file="$repo_root/.planning/phases/29-public-docs-onboarding-pricing-and-operator-guides/29-01-PLAN.md"
phase29_verification_file="$repo_root/.planning/phases/29-public-docs-onboarding-pricing-and-operator-guides/29-VERIFICATION.md"
phase29_summary_file="$repo_root/.planning/phases/29-public-docs-onboarding-pricing-and-operator-guides/29-01-SUMMARY.md"
phase30_context_file="$repo_root/.planning/phases/30-end-to-end-commercial-journey-and-final-audit/30-CONTEXT.md"
phase30_plan_file="$repo_root/.planning/phases/30-end-to-end-commercial-journey-and-final-audit/30-01-PLAN.md"
phase30_verification_file="$repo_root/.planning/phases/30-end-to-end-commercial-journey-and-final-audit/30-VERIFICATION.md"
phase30_summary_file="$repo_root/.planning/phases/30-end-to-end-commercial-journey-and-final-audit/30-01-SUMMARY.md"
commercial_completion_audit_file="$repo_root/docs/release/commercial-completion-audit.md"
commercial_completion_verifier_file="$repo_root/scripts/verify-commercial-completion.sh"
commercial_journey_backend_test_file="$repo_root/src/server/internal/http/commercial_journey_test.go"
commercial_journey_e2e_file="$repo_root/src/web/e2e/commercial-journey.spec.ts"
commercial_journey_fixture_file="$repo_root/src/web/e2e/fixtures/commercialJourney.ts"
chat_web_page_file="$repo_root/src/web/src/routes/workspace/ChatPage.tsx"
solo_web_page_file="$repo_root/src/web/src/routes/workspace/SoloPage.tsx"
marketplace_detail_page_file="$repo_root/src/web/src/routes/marketplace/MarketplaceAgentDetailPage.tsx"
marketplace_publish_page_file="$repo_root/src/web/src/routes/marketplace/MarketplacePublishPage.tsx"
marketplace_my_agents_page_file="$repo_root/src/web/src/routes/marketplace/MarketplaceMyAgentsPage.tsx"
admin_home_page_file="$repo_root/src/web/src/routes/admin/AdminHomePage.tsx"
admin_billing_page_file="$repo_root/src/web/src/routes/admin/AdminBillingPage.tsx"
admin_reviews_page_file="$repo_root/src/web/src/routes/admin/AdminReviewsPage.tsx"

assert_file_exists "$workflow_file"
assert_file_exists "$readme_file"
assert_file_exists "$api_file"
assert_file_exists "$contracts_file"
assert_file_exists "$release_checklist_file"
assert_file_exists "$commercial_gates_file"
assert_file_exists "$relay_route_table_file"
assert_file_exists "$phase16_verification_file"
assert_file_exists "$deployment_remediation_file"
assert_file_exists "$backup_restore_runbook_file"
assert_file_exists "$observability_slos_file"
assert_file_exists "$release_rollback_runbook_file"
assert_file_exists "$incident_response_runbook_file"
assert_file_exists "$disaster_recovery_runbook_file"
assert_file_exists "$v07_operations_evidence_file"
assert_file_exists "$product_overview_file"
assert_file_exists "$product_onboarding_file"
assert_file_exists "$product_pricing_file"
assert_file_exists "$product_operator_guide_file"
assert_file_exists "$dockerfile_server_file"
assert_file_exists "$dockerfile_web_file"
assert_file_exists "$dockerignore_file"
assert_file_exists "$compose_file"
assert_file_exists "$deploy_smoke_file"
assert_file_exists "$deploy_validate_file"
assert_file_exists "$backup_postgres_file"
assert_file_exists "$restore_postgres_file"
assert_file_exists "$backup_restore_smoke_file"
assert_file_exists "$relay_security_file"
assert_file_exists "$k8s_namespace_file"
assert_file_exists "$k8s_configmap_file"
assert_file_exists "$k8s_secret_example_file"
assert_file_exists "$k8s_postgres_file"
assert_file_exists "$k8s_redis_file"
assert_file_exists "$k8s_server_file"
assert_file_exists "$k8s_web_file"
assert_file_exists "$observability_alerts_file"
assert_file_exists "$observability_dashboard_file"
assert_file_exists "$owner_matrix_file"
assert_file_exists "$weekly_status_file"
assert_file_exists "$blocker_escalation_file"
assert_file_exists "$builtin_mcp_file"
assert_file_exists "$agent_workflow_migration_file"
assert_file_exists "$agent_store_file"
assert_file_exists "$agent_store_test_file"
assert_file_exists "$agent_service_test_file"
assert_file_exists "$agent_http_handler_test_file"
assert_file_exists "$phase25_context_file"
assert_file_exists "$phase25_plan_file"
assert_file_exists "$phase26_context_file"
assert_file_exists "$phase26_plan_file"
assert_file_exists "$phase26_verification_file"
assert_file_exists "$phase26_summary_file"
assert_file_exists "$knowledge_rag_migration_file"
assert_file_exists "$knowledge_service_file"
assert_file_exists "$knowledge_store_file"
assert_file_exists "$knowledge_service_test_file"
assert_file_exists "$knowledge_store_test_file"
assert_file_exists "$knowledge_http_handler_test_file"
assert_file_exists "$knowledge_router_file"
assert_file_exists "$knowledge_web_page_file"
assert_file_exists "$knowledge_web_test_file"
assert_file_exists "$web_api_types_file"
assert_file_exists "$phase27_context_file"
assert_file_exists "$phase27_plan_file"
assert_file_exists "$phase27_verification_file"
assert_file_exists "$phase27_summary_file"
assert_file_exists "$phase28_context_file"
assert_file_exists "$phase28_plan_file"
assert_file_exists "$phase28_verification_file"
assert_file_exists "$phase28_summary_file"
assert_file_exists "$phase29_context_file"
assert_file_exists "$phase29_plan_file"
assert_file_exists "$phase29_verification_file"
assert_file_exists "$phase29_summary_file"
assert_file_exists "$phase30_context_file"
assert_file_exists "$phase30_plan_file"
assert_file_exists "$phase30_verification_file"
assert_file_exists "$phase30_summary_file"
assert_file_exists "$commercial_completion_audit_file"
assert_file_exists "$commercial_completion_verifier_file"
assert_file_exists "$commercial_journey_backend_test_file"
assert_file_exists "$commercial_journey_e2e_file"
assert_file_exists "$commercial_journey_fixture_file"
assert_file_exists "$chat_web_page_file"
assert_file_exists "$solo_web_page_file"
assert_file_exists "$marketplace_detail_page_file"
assert_file_exists "$marketplace_publish_page_file"
assert_file_exists "$marketplace_my_agents_page_file"
assert_file_exists "$admin_home_page_file"
assert_file_exists "$admin_billing_page_file"
assert_file_exists "$admin_reviews_page_file"

assert_file_not_contains "$workflow_file" "phase0-task1-contracts"
assert_file_contains "$workflow_file" "web:"
assert_file_contains "$workflow_file" "server:"
assert_file_contains "$workflow_file" "pgvector/pgvector:pg16"
assert_file_contains "$workflow_file" "TEST_DATABASE_URL"
assert_file_contains "$workflow_file" "OBLIVIOUS_REQUIRE_TEST_DATABASE"
assert_file_contains "$workflow_file" "bash scripts/check.sh"
assert_file_contains "$workflow_file" "bash scripts/check.sh relay-security"
assert_file_contains "$workflow_file" "bash scripts/test.sh"
assert_file_contains "$workflow_file" "bash scripts/test.sh server"

assert_file_contains "$package_file" '"dev": "bash scripts/dev.sh"'
assert_file_contains "$package_file" '"check": "bash scripts/check.sh"'
assert_file_contains "$package_file" '"test": "bash scripts/test.sh"'

assert_file_not_contains "$workspace_file" '"lobehub"'
assert_file_not_contains "$workspace_file" '"new-api"'
assert_file_contains "$gitignore_file" ".superpowers/"

assert_file_contains "$readme_file" "## Quick Start"
assert_file_contains "$readme_file" "multi-tenant AI SaaS"
assert_file_contains "$readme_file" "Relay"
assert_file_contains "$readme_file" "docs/product/public-overview.md"
assert_file_contains "$readme_file" "docs/product/onboarding.md"
assert_file_contains "$readme_file" "docs/product/pricing.md"
assert_file_contains "$readme_file" "docs/product/operator-guide.md"
assert_file_contains "$readme_file" "Phase 30"
assert_file_contains "$readme_file" "no-final-readiness"
assert_file_contains "$readme_file" "bash scripts/check.sh"
assert_file_contains "$readme_file" "bash scripts/test.sh"
assert_file_contains "$readme_file" "docs/API.md"
assert_file_contains "$readme_file" "docs/release/rc-checklist.md"
assert_file_contains "$readme_file" "docs/release/commercial-gates.md"
assert_file_not_contains "$readme_file" ".worktrees/phase0-task1-contracts"

assert_file_contains "$product_overview_file" "PROD-05"
assert_file_contains "$product_overview_file" "multi-tenant AI SaaS"
assert_file_contains "$product_overview_file" "Chat"
assert_file_contains "$product_overview_file" "Agent"
assert_file_contains "$product_overview_file" "RAG"
assert_file_contains "$product_overview_file" "Relay"
assert_file_contains "$product_overview_file" "Marketplace"
assert_file_contains "$product_overview_file" "subscription"
assert_file_contains "$product_overview_file" "top-up"
assert_file_contains "$product_overview_file" "Phase 30"
assert_file_contains "$product_overview_file" "no-final-readiness"
assert_file_contains "$product_onboarding_file" "PROD-05"
assert_file_contains "$product_onboarding_file" "onboarding"
assert_file_contains "$product_onboarding_file" "organization"
assert_file_contains "$product_onboarding_file" "Relay"
assert_file_contains "$product_onboarding_file" "subscription"
assert_file_contains "$product_onboarding_file" "top-up"
assert_file_contains "$product_onboarding_file" "Phase 30"
assert_file_contains "$product_onboarding_file" "no-final-readiness"
assert_file_contains "$product_pricing_file" "PROD-05"
assert_file_contains "$product_pricing_file" "pricing"
assert_file_contains "$product_pricing_file" "subscription"
assert_file_contains "$product_pricing_file" "top-up"
assert_file_contains "$product_pricing_file" "quota"
assert_file_contains "$product_pricing_file" "Marketplace settlement"
assert_file_contains "$product_pricing_file" "Phase 30"
assert_file_contains "$product_pricing_file" "no-final-readiness"
assert_file_contains "$product_operator_guide_file" "PROD-05"
assert_file_contains "$product_operator_guide_file" "operator guide"
assert_file_contains "$product_operator_guide_file" "deploy"
assert_file_contains "$product_operator_guide_file" "backup"
assert_file_contains "$product_operator_guide_file" "restore"
assert_file_contains "$product_operator_guide_file" "Phase 30"
assert_file_contains "$product_operator_guide_file" "no-final-readiness"

assert_file_contains "$api_file" "## Admin Endpoints"
assert_file_contains "$api_file" "v08 commercial product completeness"
assert_file_contains "$api_file" "## Marketplace Endpoints"
assert_file_contains "$api_file" "## Relay /v1 Endpoints"
assert_file_contains "$api_file" "/api/v1/admin/channels"
assert_file_contains "$api_file" "/api/v1/marketplace/search"
assert_file_contains "$api_file" "/v1/chat/completions"
assert_file_contains "$api_file" "docs/release/relay-route-table.md"
assert_file_contains "$api_file" "Default commercial Agent tool exposure is policy-gated"
assert_file_contains "$api_file" "calculator"
assert_file_contains "$api_file" "datetime"
assert_file_contains "$api_file" "web_search"
assert_file_contains "$api_file" "Disabled by default until a real search provider is configured"
assert_file_contains "$api_file" "http_request"
assert_file_contains "$api_file" "Disabled by default until a tenant-safe outbound HTTP policy is configured"
assert_file_contains "$api_file" "/api/v1/app/agents/conversations/:conversationId/runs"
assert_file_contains "$api_file" "/api/v1/app/agents/runs/:runId"
assert_file_contains "$api_file" "/api/v1/app/agents/tool-runs/:toolRunId/approve"
assert_file_contains "$api_file" "/api/v1/app/agents/tool-runs/:toolRunId/reject"
assert_file_contains "$api_file" "/api/v1/app/agents/tool-runs/:toolRunId/retry"
assert_file_contains "$api_file" "agent_runs"
assert_file_contains "$api_file" "agent_tool_runs"
assert_file_contains "$api_file" "requiresApproval"
assert_file_contains "$api_file" 'Relay `/v1/embeddings`'
assert_file_contains "$api_file" "pgvector"
assert_file_contains "$api_file" "source-cited RAG"
assert_file_contains "$api_file" "retrievalMethod"
assert_file_contains "$api_file" "embedding_rag"
assert_file_contains "$api_file" "source.documentTitle"
assert_file_contains "$api_file" "source.chunkIndex"

assert_file_contains "$contracts_file" "/api/v1/admin/stats"
assert_file_contains "$contracts_file" "/api/v1/marketplace/featured"
assert_file_contains "$contracts_file" "/marketplace/my-agents"
assert_file_contains "$contracts_file" "COREPACK_HOME=.tmp/corepack pnpm --dir src/web test:e2e"
assert_file_contains "$contracts_file" "lobehub/"
assert_file_contains "$contracts_file" "new-api/"
assert_file_contains "$contracts_file" "v08 Product Completeness"
assert_file_contains "$contracts_file" "Relay embeddings"
assert_file_contains "$contracts_file" "pgvector"
assert_file_contains "$contracts_file" "embedding_rag"
assert_file_contains "$contracts_file" "agent_runs"
assert_file_contains "$contracts_file" "agent_tool_runs"
assert_file_contains "$contracts_file" "no-final-readiness"

assert_file_contains "$release_checklist_file" "Web production build"
assert_file_contains "$release_checklist_file" "Docs and release assets"
assert_file_contains "$release_checklist_file" "Server release checks"
assert_file_contains "$release_checklist_file" "Documentation Evidence"
assert_file_contains "$release_checklist_file" "No P0/P1 defects open"
assert_file_contains "$release_checklist_file" "TEST_DATABASE_URL"
assert_file_contains "$release_checklist_file" "pnpm --dir src/web test:e2e"
assert_file_contains "$release_checklist_file" "Known accepted debt"
assert_file_contains "$release_checklist_file" "commercial-gates.md"
assert_file_contains "$release_checklist_file" "No live provider keys required"
assert_file_contains "$release_checklist_file" "docker compose build"
assert_file_contains "$release_checklist_file" "bash scripts/deploy-validate.sh"
assert_file_contains "$release_checklist_file" "bash scripts/deploy-smoke.sh"
assert_file_contains "$release_checklist_file" "kubectl apply -f deploy/kubernetes/"
assert_file_contains "$release_checklist_file" "deployment-runtime-remediation.md"
assert_file_not_contains "$release_checklist_file" ".worktrees/phase0-task1-contracts"

assert_file_contains "$commercial_gates_file" "Commercial Readiness Gates"
assert_file_contains "$commercial_gates_file" "Tenant And Identity Gate"
assert_file_contains "$commercial_gates_file" "Relay Authority Gate"
assert_file_contains "$commercial_gates_file" "Billing And Monetization Gate"
assert_file_contains "$commercial_gates_file" "Product Completeness Gate"
assert_file_contains "$commercial_gates_file" "Security Gate"
assert_file_contains "$commercial_gates_file" "Operations Gate"
assert_file_contains "$commercial_gates_file" "Verification Gate"
assert_file_contains "$commercial_gates_file" "v05"
assert_file_contains "$commercial_gates_file" "v06"
assert_file_contains "$commercial_gates_file" "v07"
assert_file_contains "$commercial_gates_file" "v08"
assert_file_contains "$commercial_gates_file" "docs/release/relay-route-table.md"
assert_file_contains "$commercial_gates_file" "backup-restore-smoke"
assert_file_contains "$commercial_gates_file" "scripts/verify-relay-security.sh"
assert_file_contains "$commercial_gates_file" "Relay Authority Gate closeout evidence"
assert_file_contains "$commercial_gates_file" "observability-slos.md"
assert_file_contains "$commercial_gates_file" "OPS-04"
assert_file_contains "$commercial_gates_file" "OPS-05"
assert_file_contains "$commercial_gates_file" "Phase 24"
assert_file_contains "$commercial_gates_file" "Phase 25"
assert_file_contains "$commercial_gates_file" "PROD-01"
assert_file_contains "$commercial_gates_file" "PROD-02"
assert_file_contains "$commercial_gates_file" "Phase 26"
assert_file_contains "$commercial_gates_file" "agent_runs"
assert_file_contains "$commercial_gates_file" "agent_tool_runs"
assert_file_contains "$commercial_gates_file" "approval/reject/retry"
assert_file_contains "$commercial_gates_file" "PROD-03"
assert_file_contains "$commercial_gates_file" "Phase 27"
assert_file_contains "$commercial_gates_file" "Relay embeddings"
assert_file_contains "$commercial_gates_file" "pgvector chunk retrieval"
assert_file_contains "$commercial_gates_file" "embedding_rag"
assert_file_contains "$commercial_gates_file" "source citations"
assert_file_contains "$commercial_gates_file" "PROD-04"
assert_file_contains "$commercial_gates_file" "Phase 28"
assert_file_contains "$commercial_gates_file" "Commercial UX"
assert_file_contains "$commercial_gates_file" "PROD-05"
assert_file_contains "$commercial_gates_file" "Phase 29"
assert_file_contains "$commercial_gates_file" "public docs"
assert_file_contains "$commercial_gates_file" "onboarding"
assert_file_contains "$commercial_gates_file" "pricing"
assert_file_contains "$commercial_gates_file" "operator guides"
assert_file_contains "$commercial_gates_file" "Phase 30"
assert_file_contains "$commercial_gates_file" "web_search"
assert_file_contains "$commercial_gates_file" "http_request"
assert_file_contains "$commercial_gates_file" "disabled by default"

assert_file_contains "$builtin_mcp_file" "ListDefaultCommercialBuiltinTools"
assert_file_contains "$builtin_mcp_file" "defaultCommercialBuiltinEnabled"
assert_file_contains "$builtin_mcp_file" "\"calculator\":   true"
assert_file_contains "$builtin_mcp_file" "\"datetime\":     true"
assert_file_contains "$builtin_mcp_file" "\"web_search\":   false"
assert_file_contains "$builtin_mcp_file" "\"http_request\": false"
assert_file_not_contains "$builtin_mcp_file" "placeholder - integrate with search API"
assert_file_not_contains "$builtin_mcp_file" "placeholder - implement expression parser"
assert_file_contains "$phase25_context_file" "PROD-01"
assert_file_contains "$phase25_plan_file" "PROD-01"
assert_file_contains "$agent_workflow_migration_file" "agent_runs"
assert_file_contains "$agent_workflow_migration_file" "agent_tool_runs"
assert_file_contains "$agent_workflow_migration_file" "approval_status"
assert_file_contains "$agent_store_file" "RequiresApproval"
assert_file_contains "$agent_store_file" "RunStatusPendingApproval"
assert_file_contains "$agent_service_test_file" "ApprovalRequired"
assert_file_contains "$agent_service_test_file" "MemoryEvidence"
assert_file_contains "$agent_http_handler_test_file" "AgentRun"
assert_file_contains "$agent_http_handler_test_file" "Approval"
assert_file_contains "$agent_http_handler_test_file" "Retry"
assert_file_contains "$agent_http_handler_test_file" "Tenant"
assert_file_contains "$phase26_context_file" "PROD-02"
assert_file_contains "$phase26_plan_file" "PROD-02"
assert_file_contains "$phase26_verification_file" "PROD-02"
assert_file_contains "$phase26_verification_file" "Phase 27"
assert_file_contains "$phase26_summary_file" "PROD-02"
assert_file_contains "$knowledge_rag_migration_file" "CREATE EXTENSION IF NOT EXISTS vector"
assert_file_contains "$knowledge_rag_migration_file" "knowledge_document_chunks"
assert_file_contains "$knowledge_rag_migration_file" "embedding vector(1536)"
assert_file_contains "$knowledge_rag_migration_file" "embedding_model"
assert_file_contains "$knowledge_rag_migration_file" "indexed_at"
assert_file_contains "$knowledge_rag_migration_file" "hnsw"
assert_file_contains "$knowledge_service_file" "KnowledgeEmbedder"
assert_file_contains "$knowledge_service_file" "NewServiceWithEmbedder"
assert_file_contains "$knowledge_service_file" "KnowledgeCitation"
assert_file_contains "$knowledge_service_file" "RetrievalMethod"
assert_file_contains "$knowledge_service_file" "embedding_rag"
assert_file_contains "$knowledge_service_file" "WithTrustedOrganizationID"
assert_file_contains "$knowledge_store_file" "<=>"
assert_file_contains "$knowledge_store_file" "Similarity"
assert_file_contains "$knowledge_store_file" "RetrievalMethod"
assert_file_contains "$knowledge_store_file" "KnowledgeCitation"
assert_file_contains "$knowledge_store_file" 'organization_id = $1'
assert_file_contains "$knowledge_service_test_file" "EmbedBatch"
assert_file_contains "$knowledge_service_test_file" "embedding_rag"
assert_file_contains "$knowledge_service_test_file" "Source"
assert_file_contains "$knowledge_store_test_file" "Similarity"
assert_file_contains "$knowledge_store_test_file" "CrossTenant"
assert_file_contains "$knowledge_http_handler_test_file" "chunkId"
assert_file_contains "$knowledge_http_handler_test_file" "retrievalMethod"
assert_file_contains "$knowledge_http_handler_test_file" "source"
assert_file_contains "$knowledge_router_file" "NewRelayEmbedder"
assert_file_contains "$knowledge_router_file" "NewServiceWithEmbedder"
assert_file_contains "$knowledge_web_page_file" "RAG citations"
assert_file_contains "$knowledge_web_page_file" "Source:"
assert_file_contains "$knowledge_web_page_file" "retrievalMethod"
assert_file_contains "$knowledge_web_test_file" "Source:"
assert_file_contains "$knowledge_web_test_file" "embedding_rag"
assert_file_contains "$web_api_types_file" "KnowledgeRetrievalSource"
assert_file_contains "$web_api_types_file" "retrievalMethod"
assert_file_contains "$phase27_context_file" "PROD-03"
assert_file_contains "$phase27_plan_file" "PROD-03"
assert_file_contains "$phase27_verification_file" "PROD-03"
assert_file_contains "$phase27_verification_file" "Phase 28"
assert_file_contains "$phase27_summary_file" "PROD-03"
assert_file_contains "$phase28_context_file" "PROD-04"
assert_file_contains "$phase28_context_file" "Commercial UX"
assert_file_contains "$phase28_context_file" "customer journeys"
assert_file_contains "$phase28_context_file" "This phase must not claim final commercial readiness."
assert_file_contains "$phase28_plan_file" "PROD-04"
assert_file_contains "$phase28_plan_file" "Commercial UX"
assert_file_contains "$phase28_plan_file" "placeholder"
assert_file_contains "$phase28_plan_file" "fake"
assert_file_contains "$phase28_plan_file" "Phase 28 closes only PROD-04"
assert_file_contains "$phase28_verification_file" "PROD-04"
assert_file_contains "$phase28_verification_file" "ChatPage SoloPage KnowledgePage MarketplacePage AdminHomePage AdminBillingPage AdminReviewsPage"
assert_file_contains "$phase28_verification_file" "Phase 29"
assert_file_contains "$phase28_summary_file" "PROD-04"
assert_file_contains "$phase28_summary_file" "Phase 29"
assert_file_contains "$phase29_context_file" "PROD-05"
assert_file_contains "$phase29_context_file" "Public Docs Onboarding Pricing and Operator Guides"
assert_file_contains "$phase29_context_file" "no-final-readiness"
assert_file_contains "$phase29_plan_file" "PROD-05"
assert_file_contains "$phase29_plan_file" "docs/product/public-overview.md"
assert_file_contains "$phase29_plan_file" "docs/product/onboarding.md"
assert_file_contains "$phase29_plan_file" "docs/product/pricing.md"
assert_file_contains "$phase29_plan_file" "docs/product/operator-guide.md"
assert_file_contains "$phase29_plan_file" "Phase 30"
assert_file_contains "$phase29_verification_file" "PROD-05"
assert_file_contains "$phase29_verification_file" "bash scripts/check.sh docs"
assert_file_contains "$phase29_verification_file" "git diff --check"
assert_file_contains "$phase29_verification_file" "Phase 30"
assert_file_contains "$phase29_summary_file" "PROD-05"
assert_file_contains "$phase29_summary_file" "Phase 30"
assert_file_contains "$phase30_context_file" "PROD-06"
assert_file_contains "$phase30_context_file" "AUDIT-01"
assert_file_contains "$phase30_context_file" "End-to-End Commercial Journey and Final Audit"
assert_file_contains "$phase30_context_file" "scripts/verify-commercial-completion.sh"
assert_file_contains "$phase30_plan_file" "PROD-06"
assert_file_contains "$phase30_plan_file" "AUDIT-01"
assert_file_contains "$phase30_plan_file" "src/server/internal/http/commercial_journey_test.go"
assert_file_contains "$phase30_plan_file" "src/web/e2e/commercial-journey.spec.ts"
assert_file_contains "$phase30_plan_file" "scripts/verify-commercial-completion.sh"
assert_file_contains "$phase30_plan_file" "docs/release/commercial-completion-audit.md"
assert_file_contains "$phase30_plan_file" "COMMERCIAL_COMPLETION_ALLOW_ENV_SKIPS"
assert_file_contains "$phase30_verification_file" "PROD-06"
assert_file_contains "$phase30_verification_file" "AUDIT-01"
assert_file_contains "$phase30_verification_file" "scripts/verify-commercial-completion.sh"
assert_file_contains "$phase30_verification_file" "skipped checks: none"
assert_file_contains "$phase30_summary_file" "PROD-06"
assert_file_contains "$phase30_summary_file" "AUDIT-01"
assert_file_contains "$phase30_summary_file" "Skipped checks: none"
assert_file_contains "$commercial_journey_backend_test_file" "TestCommercialHTTPJourney"
assert_file_contains "$commercial_journey_backend_test_file" "registerHTTPUser"
assert_file_contains "$commercial_journey_backend_test_file" "Relay"
assert_file_contains "$commercial_journey_backend_test_file" "Marketplace"
assert_file_contains "$commercial_journey_backend_test_file" "Admin billing"
assert_file_contains "$commercial_journey_e2e_file" "commercial journey"
assert_file_contains "$commercial_journey_e2e_file" "Chat"
assert_file_contains "$commercial_journey_e2e_file" "Knowledge"
assert_file_contains "$commercial_journey_e2e_file" "Marketplace"
assert_file_contains "$commercial_journey_e2e_file" "Admin"
assert_file_contains "$commercial_journey_fixture_file" "registerCommercialJourneyRoutes"
assert_file_contains "$commercial_journey_fixture_file" "embedding_rag"
assert_file_contains "$commercial_journey_fixture_file" "checkout-backed"
assert_file_contains "$commercial_journey_fixture_file" "settlement"
assert_file_contains "$commercial_completion_verifier_file" "commercial completion"
assert_file_contains "$commercial_completion_verifier_file" "scripts/check.sh"
assert_file_contains "$commercial_completion_verifier_file" "relay-security"
assert_file_contains "$commercial_completion_verifier_file" "commercial journey"
assert_file_contains "$commercial_completion_verifier_file" "backup-restore-smoke"
assert_file_contains "$commercial_completion_verifier_file" "COMMERCIAL_COMPLETION_ALLOW_ENV_SKIPS"
assert_file_contains "$commercial_completion_audit_file" "AUDIT-01"
assert_file_contains "$commercial_completion_audit_file" "Tenant And Identity Gate"
assert_file_contains "$commercial_completion_audit_file" "Relay Authority Gate"
assert_file_contains "$commercial_completion_audit_file" "Product Completeness Gate"
assert_file_contains "$commercial_completion_audit_file" "Verification Gate"
assert_file_not_contains "$chat_web_page_file" "fake provider"
assert_file_not_contains "$chat_web_page_file" "fake billing"
assert_file_not_contains "$chat_web_page_file" "fake settlement"
assert_file_not_contains "$solo_web_page_file" "fake provider"
assert_file_not_contains "$solo_web_page_file" "fake billing"
assert_file_not_contains "$solo_web_page_file" "fake settlement"
assert_file_not_contains "$knowledge_web_page_file" "fake RAG"
assert_file_not_contains "$marketplace_detail_page_file" "fake settlement"
assert_file_not_contains "$marketplace_publish_page_file" "fake settlement"
assert_file_not_contains "$marketplace_my_agents_page_file" "fake settlement"
assert_file_not_contains "$admin_home_page_file" "fake billing"
assert_file_not_contains "$admin_billing_page_file" "fake billing"
assert_file_not_contains "$admin_reviews_page_file" "fake settlement"

assert_file_contains "$relay_route_table_file" "Relay Route Table"
assert_file_contains "$relay_route_table_file" "CommercialSupportedBilled"
assert_file_contains "$relay_route_table_file" "DisabledInProduction"
assert_file_contains "$relay_route_table_file" "endpoint_disabled_in_production"
assert_file_contains "$relay_route_table_file" "trusted_internal_identity"
assert_file_contains "$relay_route_table_file" "global_relay_token_bucket"
assert_file_contains "$relay_route_table_file" "relay_route_policy_decision"
assert_file_contains "$relay_route_table_file" "preauthorize_then_settle_usage"
assert_file_contains "$relay_route_table_file" "preauthorize_then_settle_estimate"
assert_file_contains "$relay_route_table_file" "production_disabled"
assert_file_contains "$relay_route_table_file" "BILL-01"
assert_file_contains "$relay_route_table_file" "BILL-02"
assert_file_contains "$relay_route_table_file" "/v1/chat/completions"
assert_file_contains "$relay_route_table_file" "/v1/files"
assert_file_contains "$relay_route_table_file" "/v1/fine_tuning/jobs"
assert_file_contains "$relay_route_table_file" "/v1/threads/:id/runs"

assert_file_contains "$phase16_verification_file" "Relay Authority Gate closeout"
assert_file_contains "$phase16_verification_file" "DOC-04"
assert_file_contains "$phase16_verification_file" "bash scripts/check.sh all"
assert_file_contains "$phase16_verification_file" "bash scripts/test.sh all"
assert_file_contains "$phase16_verification_file" "v06 Billing And Marketplace Operations"
assert_file_contains "$phase16_verification_file" "v07 Production Operations"
assert_file_contains "$phase16_verification_file" "v08 Product Completeness"

assert_file_contains "$deployment_remediation_file" "bash scripts/deploy-validate.sh"
assert_file_contains "$deployment_remediation_file" "docker info"
assert_file_contains "$deployment_remediation_file" "kubectl apply -f deploy/kubernetes/"
assert_file_contains "$deployment_remediation_file" "DEPLOY_VALIDATE_DOCKER_UP_TIMEOUT_SECONDS"
assert_file_contains "$backup_restore_runbook_file" "pg_dump"
assert_file_contains "$backup_restore_runbook_file" "pg_restore"
assert_file_contains "$backup_restore_runbook_file" "BACKUP_DATABASE_URL"
assert_file_contains "$backup_restore_runbook_file" "RESTORE_DATABASE_URL"
assert_file_contains "$backup_restore_runbook_file" "PG_CLIENT_IMAGE"
assert_file_contains "$backup_restore_runbook_file" "retention"
assert_file_contains "$backup_restore_runbook_file" "encryption"
assert_file_contains "$backup_restore_runbook_file" "schema_migrations"
assert_file_contains "$observability_slos_file" "OPS-04"
assert_file_contains "$observability_slos_file" "OPS-05"
assert_file_contains "$observability_slos_file" "Relay outage"
assert_file_contains "$observability_slos_file" "quota settlement"
assert_file_contains "$observability_slos_file" "webhook failure"
assert_file_contains "$observability_slos_file" "migration failure"
assert_file_contains "$observability_slos_file" "tenant isolation"
assert_file_contains "$observability_slos_file" "final commercial readiness"
assert_file_contains "$observability_slos_file" "Phase 24"
assert_file_contains "$observability_slos_file" "v08 Product Completeness"
assert_file_contains "$observability_slos_file" "relay_route_decisions_total"
assert_file_contains "$observability_slos_file" "provider_failures_total"
assert_file_contains "$observability_slos_file" "billing_lifecycle_events_total"
assert_file_contains "$observability_slos_file" "quota_settlement_failures_total"
assert_file_contains "$observability_slos_file" "stripe_webhook_failures_total"
assert_file_contains "$observability_slos_file" "marketplace_settlement_events_total"
assert_file_contains "$observability_slos_file" "migration_runs_total"
assert_file_contains "$observability_slos_file" "release-rollback-runbook.md"
assert_file_contains "$observability_slos_file" "incident-response-runbook.md"
assert_file_contains "$observability_slos_file" "disaster-recovery-runbook.md"
assert_file_contains "$release_rollback_runbook_file" "scripts/deploy-validate.sh"
assert_file_contains "$release_rollback_runbook_file" "scripts/deploy-smoke.sh"
assert_file_contains "$release_rollback_runbook_file" "scripts/backup-postgres.sh"
assert_file_contains "$release_rollback_runbook_file" "scripts/restore-postgres.sh"
assert_file_contains "$release_rollback_runbook_file" "restricted-network"
assert_file_contains "$release_rollback_runbook_file" "OBLIVIOUS_K8S_SECRET_FILE"
assert_file_contains "$release_rollback_runbook_file" "rollback"
assert_file_contains "$release_rollback_runbook_file" "v08 Product Completeness"
assert_file_contains "$incident_response_runbook_file" "RelayOutage"
assert_file_contains "$incident_response_runbook_file" "QuotaSettlementFailure"
assert_file_contains "$incident_response_runbook_file" "StripeWebhookFailure"
assert_file_contains "$incident_response_runbook_file" "MigrationFailure"
assert_file_contains "$incident_response_runbook_file" "HighProviderErrorRate"
assert_file_contains "$incident_response_runbook_file" "TenantIsolationIncident"
assert_file_contains "$incident_response_runbook_file" "Relay-only"
assert_file_contains "$incident_response_runbook_file" "tenant isolation"
assert_file_contains "$disaster_recovery_runbook_file" "backup-restore-smoke"
assert_file_contains "$disaster_recovery_runbook_file" "restore-postgres"
assert_file_contains "$disaster_recovery_runbook_file" "schema_migrations"
assert_file_contains "$disaster_recovery_runbook_file" "deploy-validate"
assert_file_contains "$disaster_recovery_runbook_file" "deploy-smoke"
assert_file_contains "$disaster_recovery_runbook_file" "no-final-readiness"
assert_file_contains "$v07_operations_evidence_file" "OPS-01"
assert_file_contains "$v07_operations_evidence_file" "OPS-02"
assert_file_contains "$v07_operations_evidence_file" "OPS-03"
assert_file_contains "$v07_operations_evidence_file" "OPS-04"
assert_file_contains "$v07_operations_evidence_file" "OPS-05"
assert_file_contains "$v07_operations_evidence_file" "OPS-06"
assert_file_contains "$v07_operations_evidence_file" "DOC-06"
assert_file_contains "$v07_operations_evidence_file" "v08 Product Completeness"
assert_file_contains "$v07_operations_evidence_file" "no-final-readiness"
assert_file_contains "$observability_alerts_file" "RelayOutage"
assert_file_contains "$observability_alerts_file" "QuotaSettlementFailure"
assert_file_contains "$observability_alerts_file" "StripeWebhookFailure"
assert_file_contains "$observability_alerts_file" "MigrationFailure"
assert_file_contains "$observability_alerts_file" "HighProviderErrorRate"
assert_file_contains "$observability_alerts_file" "TenantIsolationIncident"
assert_file_contains "$observability_alerts_file" "severity:"
assert_file_contains "$observability_alerts_file" "owner:"
assert_file_contains "$observability_alerts_file" "relay_route_decisions_total"
assert_file_contains "$observability_alerts_file" "provider_failures_total"
assert_file_contains "$observability_alerts_file" "quota_settlement_failures_total"
assert_file_contains "$observability_alerts_file" "stripe_webhook_failures_total"
assert_file_contains "$observability_alerts_file" "migration_runs_total"
assert_file_contains "$observability_dashboard_file" "Oblivious Production Operations"
assert_file_contains "$observability_dashboard_file" "OPS-04"
assert_file_contains "$observability_dashboard_file" "OPS-05"
assert_file_contains "$observability_dashboard_file" "relay_route_decisions_total"
assert_file_contains "$observability_dashboard_file" "provider_failures_total"
assert_file_contains "$observability_dashboard_file" "billing_lifecycle_events_total"
assert_file_contains "$observability_dashboard_file" "stripe_webhook_failures_total"
assert_file_contains "$observability_dashboard_file" "marketplace_settlement_events_total"
assert_file_contains "$observability_dashboard_file" "migration_runs_total"

assert_file_contains "$dockerfile_server_file" "src/server/cmd/server"
assert_file_contains "$dockerfile_server_file" "EXPOSE 8080"
assert_file_count_at_least "$dockerfile_server_file" "target=/go/pkg/mod" 3
assert_file_contains "$dockerfile_web_file" "pnpm --dir src/web build"
assert_file_contains "$dockerfile_postgres_pgvector_file" "PGVECTOR_VERSION=v0.8.2"
assert_file_contains "$dockerfile_postgres_pgvector_file" "postgresql-server-dev-16_16.13-1.pgdg13+1_amd64.deb"
assert_file_contains "$dockerfile_postgres_pgvector_file" "make install"
assert_file_contains "$dockerignore_file" "node_modules"
assert_file_contains "$dockerignore_file" ".worktrees"
assert_file_contains "$dockerignore_file" "new-api"
assert_file_contains "$compose_file" "oblivious-server"
assert_file_contains "$compose_file" "oblivious-web"
assert_file_contains "$compose_file" "OBLIVIOUS_POSTGRES_IMAGE"
assert_file_contains "$compose_file" "pgvector/pgvector:pg16"
assert_file_contains "$compose_file" "redis:7"
assert_file_contains "$compose_file" "DATABASE_URL=postgres://oblivious:oblivious@postgres:5432/oblivious?sslmode=disable"
assert_file_not_contains "$compose_file" "sk-"
assert_file_contains "$deploy_smoke_file" 'BASE_URL="${BASE_URL:-http://127.0.0.1:8080}"'
assert_file_contains "$deploy_smoke_file" "/healthz"
assert_file_contains "$deploy_smoke_file" "healthz ok"
assert_file_contains "$deploy_validate_file" "docker compose build"
assert_file_contains "$deploy_validate_file" "docker compose up -d"
assert_file_contains "$deploy_validate_file" "bash scripts/deploy-smoke.sh"
assert_file_contains "$deploy_validate_file" "docker daemon is not reachable"
assert_file_contains "$deploy_validate_file" "DEPLOY_VALIDATE_DOCKER_UP_TIMEOUT_SECONDS"
assert_file_contains "$backup_postgres_file" "pg_dump"
assert_file_contains "$backup_postgres_file" "--format=custom"
assert_file_contains "$backup_postgres_file" ".tmp/backups"
assert_file_contains "$restore_postgres_file" "pg_restore"
assert_file_contains "$restore_postgres_file" "schema_migrations"
assert_file_contains "$restore_postgres_file" "sha256sum"
assert_file_contains "$backup_restore_smoke_file" "phase22_"
assert_file_contains "$backup_restore_smoke_file" "backup-postgres.sh"
assert_file_contains "$backup_restore_smoke_file" "restore-postgres.sh"
assert_file_contains "$backup_restore_smoke_file" "schema_migrations"
assert_file_contains "$relay_security_file" "app services are Relay-only for provider calls"
assert_file_contains "$relay_security_file" "NewHTTPReplyGenerator"
assert_file_contains "$relay_security_file" "TenantIdentityRequired"
assert_file_contains "$k8s_namespace_file" "name: oblivious"
assert_file_contains "$k8s_configmap_file" "RELAY_ENABLED"
assert_file_contains "$k8s_secret_example_file" "REPLACE_ME"
assert_file_contains "$k8s_server_file" "/healthz"
assert_file_contains "$k8s_postgres_file" "pgvector/pgvector:pg16"
assert_file_contains "$k8s_server_file" "oblivious-server:local"
assert_file_contains "$k8s_web_file" "oblivious-web:local"
for k8s_file in "$repo_root"/deploy/kubernetes/*.yaml; do
  assert_file_not_contains "$k8s_file" "sk-"
done

assert_file_contains "$owner_matrix_file" "| TL |"
assert_file_contains "$owner_matrix_file" "| FE |"
assert_file_contains "$owner_matrix_file" "| BE |"
assert_file_contains "$weekly_status_file" "Actual Owner:"
assert_file_contains "$weekly_status_file" "## Risks / Blockers"
assert_file_contains "$blocker_escalation_file" "| Severity | Definition | Response Window | Escalate To |"

assert_file_contains "$check_script" "scripts/verify-quality-gates.sh"
assert_file_contains "$check_script" "scripts/verify-relay-security.sh"
assert_file_contains "$check_script" "relay-security"
assert_file_contains "$check_script" 'workspace_file="$repo_root/pnpm-workspace.yaml"'
assert_file_contains "$check_script" 'Unexpected workspace member: lobehub'
assert_file_contains "$check_script" 'Unexpected workspace member: new-api'
assert_file_contains "$check_script" 'pnpm --dir "$web_dir" build'
assert_file_contains "$check_script" "docs/architecture/current-system-contracts.md"
assert_file_contains "$check_script" "config/.env.example"
assert_file_contains "$check_script" "go test ./... -count=1"

assert_file_contains "$test_script" "Running server unit tests."
assert_file_contains "$test_script" "Running server integration tests."
assert_file_contains "$test_script" "OBLIVIOUS_REQUIRE_TEST_DATABASE"
assert_file_contains "$test_script" "TEST_DATABASE_URL is required when OBLIVIOUS_REQUIRE_TEST_DATABASE=true."
assert_file_contains "$test_script" "Skipping server integration tests: TEST_DATABASE_URL not set."
assert_file_contains "$test_script" "go test ./... -count=1"
assert_file_contains "$test_script" "go test ./internal/http"

stale_docs_pattern="v03\\.3|text matching|SOLO.*MVP|must receive final settlement/refund proof before v05 closes|release-candidate mainline"
for doc_file in \
  "$readme_file" \
  "$api_file" \
  "$contracts_file" \
  "$product_overview_file" \
  "$product_onboarding_file" \
  "$product_pricing_file" \
  "$product_operator_guide_file" \
  "$commercial_gates_file" \
  "$commercial_completion_audit_file"; do
  assert_file_not_matches "$doc_file" "$stale_docs_pattern"
done

echo "[quality-gates] quality gate assets look complete."
