// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/observability/v1/observability.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED MetricType = 0
	MetricType_COUNTER                 MetricType = 1
	MetricType_GAUGE                   MetricType = 2
	MetricType_HISTOGRAM               MetricType = 3
	MetricType_SUMMARY                 MetricType = 4
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "COUNTER",
		2: "GAUGE",
		3: "HISTOGRAM",
		4: "SUMMARY",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED": 0,
		"COUNTER":                 1,
		"GAUGE":                   2,
		"HISTOGRAM":               3,
		"SUMMARY":                 4,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_observability_v1_observability_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_api_proto_observability_v1_observability_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_observability_v1_observability_proto_rawDescGZIP(), []int{0}
}

type PublishMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMetricsRequest) Reset() {
	*x = PublishMetricsRequest{}
	mi := &file_api_proto_observability_v1_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMetricsRequest) ProtoMessage() {}

func (x *PublishMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observability_v1_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMetricsRequest.ProtoReflect.Descriptor instead.
func (*PublishMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_observability_v1_observability_proto_rawDescGZIP(), []int{0}
}

func (x *PublishMetricsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PublishMetricsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PublishMetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PublishMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *PublishMetricsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          MetricType             `protobuf:"varint,2,opt,name=type,proto3,enum=observability.v1.MetricType" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_proto_observability_v1_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observability_v1_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_proto_observability_v1_observability_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PublishMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,3,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMetricsResponse) Reset() {
	*x = PublishMetricsResponse{}
	mi := &file_api_proto_observability_v1_observability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMetricsResponse) ProtoMessage() {}

func (x *PublishMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_observability_v1_observability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMetricsResponse.ProtoReflect.Descriptor instead.
func (*PublishMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_observability_v1_observability_proto_rawDescGZIP(), []int{2}
}

func (x *PublishMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishMetricsResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

var File_api_proto_observability_v1_observability_proto protoreflect.FileDescriptor

const file_api_proto_observability_v1_observability_proto_rawDesc = "" +
	"\n" +
	".api/proto/observability/v1/observability.proto\x12\x10observability.v1\"\xb5\x02\n" +
	"\x15PublishMetricsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x122\n" +
	"\ametrics\x18\x04 \x03(\v2\x18.observability.v1.MetricR\ametrics\x12K\n" +
	"\x06labels\x18\x05 \x03(\v23.observability.v1.PublishMetricsRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.observability.v1.MetricTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x126\n" +
	"\x04tags\x18\x04 \x03(\v2\".observability.v1.Metric.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x16PublishMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaccepted_count\x18\x03 \x01(\x05R\racceptedCount*]\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\x12\t\n" +
	"\x05GAUGE\x10\x02\x12\r\n" +
	"\tHISTOGRAM\x10\x03\x12\v\n" +
	"\aSUMMARY\x10\x042\xe7\x01\n" +
	"\x14ObservabilityService\x12c\n" +
	"\x0ePublishMetrics\x12'.observability.v1.PublishMetricsRequest\x1a(.observability.v1.PublishMetricsResponse\x12j\n" +
	"\x13PublishMetricsBatch\x12'.observability.v1.PublishMetricsRequest\x1a(.observability.v1.PublishMetricsResponse(\x01B-Z+oblivious/server/api/proto/observability/v1b\x06proto3"

var (
	file_api_proto_observability_v1_observability_proto_rawDescOnce sync.Once
	file_api_proto_observability_v1_observability_proto_rawDescData []byte
)

func file_api_proto_observability_v1_observability_proto_rawDescGZIP() []byte {
	file_api_proto_observability_v1_observability_proto_rawDescOnce.Do(func() {
		file_api_proto_observability_v1_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_observability_v1_observability_proto_rawDesc), len(file_api_proto_observability_v1_observability_proto_rawDesc)))
	})
	return file_api_proto_observability_v1_observability_proto_rawDescData
}

var file_api_proto_observability_v1_observability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_observability_v1_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_observability_v1_observability_proto_goTypes = []any{
	(MetricType)(0),                // 0: observability.v1.MetricType
	(*PublishMetricsRequest)(nil),  // 1: observability.v1.PublishMetricsRequest
	(*Metric)(nil),                 // 2: observability.v1.Metric
	(*PublishMetricsResponse)(nil), // 3: observability.v1.PublishMetricsResponse
	nil,                            // 4: observability.v1.PublishMetricsRequest.LabelsEntry
	nil,                            // 5: observability.v1.Metric.TagsEntry
}
var file_api_proto_observability_v1_observability_proto_depIdxs = []int32{
	2, // 0: observability.v1.PublishMetricsRequest.metrics:type_name -> observability.v1.Metric
	4, // 1: observability.v1.PublishMetricsRequest.labels:type_name -> observability.v1.PublishMetricsRequest.LabelsEntry
	0, // 2: observability.v1.Metric.type:type_name -> observability.v1.MetricType
	5, // 3: observability.v1.Metric.tags:type_name -> observability.v1.Metric.TagsEntry
	1, // 4: observability.v1.ObservabilityService.PublishMetrics:input_type -> observability.v1.PublishMetricsRequest
	1, // 5: observability.v1.ObservabilityService.PublishMetricsBatch:input_type -> observability.v1.PublishMetricsRequest
	3, // 6: observability.v1.ObservabilityService.PublishMetrics:output_type -> observability.v1.PublishMetricsResponse
	3, // 7: observability.v1.ObservabilityService.PublishMetricsBatch:output_type -> observability.v1.PublishMetricsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_observability_v1_observability_proto_init() }
func file_api_proto_observability_v1_observability_proto_init() {
	if File_api_proto_observability_v1_observability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_observability_v1_observability_proto_rawDesc), len(file_api_proto_observability_v1_observability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_observability_v1_observability_proto_goTypes,
		DependencyIndexes: file_api_proto_observability_v1_observability_proto_depIdxs,
		EnumInfos:         file_api_proto_observability_v1_observability_proto_enumTypes,
		MessageInfos:      file_api_proto_observability_v1_observability_proto_msgTypes,
	}.Build()
	File_api_proto_observability_v1_observability_proto = out.File
	file_api_proto_observability_v1_observability_proto_goTypes = nil
	file_api_proto_observability_v1_observability_proto_depIdxs = nil
}
