// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: api/proto/observability/v1/observability.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservabilityService_PublishMetrics_FullMethodName      = "/observability.v1.ObservabilityService/PublishMetrics"
	ObservabilityService_PublishMetricsBatch_FullMethodName = "/observability.v1.ObservabilityService/PublishMetricsBatch"
)

// ObservabilityServiceClient is the client API for ObservabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObservabilityService: metrics consumer
type ObservabilityServiceClient interface {
	PublishMetrics(ctx context.Context, in *PublishMetricsRequest, opts ...grpc.CallOption) (*PublishMetricsResponse, error)
	PublishMetricsBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PublishMetricsRequest, PublishMetricsResponse], error)
}

type observabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservabilityServiceClient(cc grpc.ClientConnInterface) ObservabilityServiceClient {
	return &observabilityServiceClient{cc}
}

func (c *observabilityServiceClient) PublishMetrics(ctx context.Context, in *PublishMetricsRequest, opts ...grpc.CallOption) (*PublishMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMetricsResponse)
	err := c.cc.Invoke(ctx, ObservabilityService_PublishMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observabilityServiceClient) PublishMetricsBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PublishMetricsRequest, PublishMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObservabilityService_ServiceDesc.Streams[0], ObservabilityService_PublishMetricsBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishMetricsRequest, PublishMetricsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_PublishMetricsBatchClient = grpc.ClientStreamingClient[PublishMetricsRequest, PublishMetricsResponse]

// ObservabilityServiceServer is the server API for ObservabilityService service.
// All implementations must embed UnimplementedObservabilityServiceServer
// for forward compatibility.
//
// ObservabilityService: metrics consumer
type ObservabilityServiceServer interface {
	PublishMetrics(context.Context, *PublishMetricsRequest) (*PublishMetricsResponse, error)
	PublishMetricsBatch(grpc.ClientStreamingServer[PublishMetricsRequest, PublishMetricsResponse]) error
	mustEmbedUnimplementedObservabilityServiceServer()
}

// UnimplementedObservabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservabilityServiceServer struct{}

func (UnimplementedObservabilityServiceServer) PublishMetrics(context.Context, *PublishMetricsRequest) (*PublishMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishMetrics not implemented")
}
func (UnimplementedObservabilityServiceServer) PublishMetricsBatch(grpc.ClientStreamingServer[PublishMetricsRequest, PublishMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method PublishMetricsBatch not implemented")
}
func (UnimplementedObservabilityServiceServer) mustEmbedUnimplementedObservabilityServiceServer() {}
func (UnimplementedObservabilityServiceServer) testEmbeddedByValue()                              {}

// UnsafeObservabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservabilityServiceServer will
// result in compilation errors.
type UnsafeObservabilityServiceServer interface {
	mustEmbedUnimplementedObservabilityServiceServer()
}

func RegisterObservabilityServiceServer(s grpc.ServiceRegistrar, srv ObservabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedObservabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservabilityService_ServiceDesc, srv)
}

func _ObservabilityService_PublishMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).PublishMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_PublishMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).PublishMetrics(ctx, req.(*PublishMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservabilityService_PublishMetricsBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObservabilityServiceServer).PublishMetricsBatch(&grpc.GenericServerStream[PublishMetricsRequest, PublishMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObservabilityService_PublishMetricsBatchServer = grpc.ClientStreamingServer[PublishMetricsRequest, PublishMetricsResponse]

// ObservabilityService_ServiceDesc is the grpc.ServiceDesc for ObservabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "observability.v1.ObservabilityService",
	HandlerType: (*ObservabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMetrics",
			Handler:    _ObservabilityService_PublishMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishMetricsBatch",
			Handler:       _ObservabilityService_PublishMetricsBatch_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/observability/v1/observability.proto",
}
