ALTER TABLE conversation_configs
    ADD COLUMN IF NOT EXISTS system_prompt_override TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS temperature DOUBLE PRECISION NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS max_output_tokens INTEGER NOT NULL DEFAULT 1024,
    ADD COLUMN IF NOT EXISTS tools_enabled BOOLEAN NOT NULL DEFAULT FALSE;
