ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS tool_allow_list TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS tool_deny_list TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
