-- Knowledge-base level RAG retrieval and chunking defaults.

ALTER TABLE IF EXISTS knowledge_bases
  ADD COLUMN IF NOT EXISTS retrieval_mode TEXT NOT NULL DEFAULT 'hybrid',
  ADD COLUMN IF NOT EXISTS retrieval_limit INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS min_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vector_weight DOUBLE PRECISION NOT NULL DEFAULT 0.7,
  ADD COLUMN IF NOT EXISTS keyword_weight DOUBLE PRECISION NOT NULL DEFAULT 0.3,
  ADD COLUMN IF NOT EXISTS reranker_model TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS rerank_top_k INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS chunk_strategy TEXT NOT NULL DEFAULT 'template_based',
  ADD COLUMN IF NOT EXISTS chunk_size INTEGER NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS chunk_overlap INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS embedding_model TEXT NOT NULL DEFAULT 'text-embedding-3-small';
